quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizzes.urls', namespace='quizzes'))
]

quizzes/urls.py
from django.urls import path
from .views import QuizListView, quiz_view, quiz_data_view, save_quiz_view


app_name = 'quizzes'

urlpatterns = [
    path('', QuizListView.as_view(), name="main-view"),
    path('<int:pk>/', quiz_view, name="quiz-view"),
    path('<int:pk>/save/', save_quiz_view, name="save-view"),
    path('<int:pk>/data/', quiz_data_view, name="quiz-data-view"),
]

questions/models.py
from django.db import models
from quizzes.models import Quiz


class Question(models.Model):
    text = models.CharField(max_length=200, verbose_name='Savol')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, verbose_name="Test")
    created = models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')

    def __str__(self):
        return f"{self.text}"

    def get_answers(self):
        return self.answer_set.all()

    class Meta:
        verbose_name = 'Savol'
        verbose_name_plural = 'Savollar'


class Answer(models.Model):
    text = models.CharField(max_length=200, verbose_name='Javoblar variantlari')
    correct = models.BooleanField(default=False, verbose_name="To'gri javob")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='Savol')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

    class Meta:
        verbose_name = 'Javob'
        verbose_name_plural = 'Javoblar'

quizzes/models.py
from django.db import models
import random

DIFF_CHOICES = (
    ('easy', 'oson'),
    ('medium', "o'rta"),
    ('hard', 'murakkab'),
)


class Quiz(models.Model):
    name = models.CharField(max_length=120, verbose_name='Test nomi')
    topic = models.CharField(max_length=120, verbose_name='Mavzusi')
    number_of_questions = models.IntegerField(verbose_name='Savollar miqdori')
    time = models.IntegerField(help_text='Sinov davomiyligi daqiqalarda', verbose_name='Sinov muddati')
    required_score_to_pass = models.IntegerField(help_text='Majburiy ball %da', verbose_name="O'tish uchun bal")
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES, verbose_name='Murakkablik')

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name = 'Test'
        verbose_name_plural = 'Testlar'

results/models.py
from django.db import models
from quizzes.models import Quiz
from django.contrib.auth.models import User


class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, verbose_name='Test')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Foydalanuvchi')
    score = models.FloatField(verbose_name="Bal")

    def __str__(self):
        return f"{self.pk}"

    class Meta:
        verbose_name = 'Natija'
        verbose_name_plural = 'Natijalar'

questions/views.py
from django.shortcuts import render

# Create your views here.

quizzes/views.py
from django.shortcuts import render
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question, Answer
from results.models import Result


class QuizListView(ListView):
    model = Quiz
    template_name = 'quizzes/main.html'


def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizzes/quiz.html', {'obj': quiz})


def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answer = []
        for a in q.get_answers():
            answer.append(a.text)
        questions.append({str(q): answer})
    return JsonResponse({
        'data': questions,
        'time': quiz.time
    })


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


def save_quiz_view(request, pk):
    if is_ajax(request):
        questions = []
        data = request.POST
        data_ = dict(data.lists())
        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key:', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text
                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ > quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})

results/views.py
from django.shortcuts import render

# Create your views here.

quizzes/templates/quizzes/main.html
{% extends 'base.html' %}
{% load static %}
{% block title %}home{% endblock title %}

{% block content %}


<!-- Модальное окно -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Testni boshlamoqchimisiz?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Yopish"></button>
            </div>
            <div class="modal-body" id="modal-body-confirm">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yopish</button>
                <button type="button" class="btn btn-primary" id="start-button">Boshlash</button>
            </div>
        </div>
    </div>
</div>

<div class="h1">Testlar:</div>
<hr>
{% for obj in object_list %}
<button
        class="btn btn-link modal-button"

        data-pk="{{ obj.pk }}"
        data-quiz="{{ obj.name }}"
        data-questions="{{ obj.number_of_questions }}"
        data-difficulty="{{ obj.difficulty }}"
        data-time="{{ obj.time }}"
        data-pass="{{ obj.required_score_to_pass }}"

        data-bs-toggle="modal"
        data-bs-target="#quizStartModal"
>{{ obj.name }}
</button><br>
{% endfor %}

{% endblock content %}

{% block scripts %}
<script src="{% static 'quizzes/main.js' %}"></script>
{% endblock scripts %}

quizzes/templates/quizzes/quiz.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ obj.name }}{% endblock title %}

{% block content %}
<div class="row">
    <div class="col">
        <h2>{{ obj.name }}</h2>
        <p>Ballar: {{ obj.required_score_to_pass }}</p>
    </div>
    <div class="col text-end" id="timer-box">orqaga sanash</div>
</div>

<a href="{% url 'quizzes:main-view' %}" class="btn btn-info">Ortga</a>

<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button class="btn btn-primary mt-3">Saqlash</button>
</form>
<div id="score-box"></div>
<div id="results-box"></div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'quizzes/quiz.js' %}"></script>
{% endblock scripts %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test qilish sistemasi | {% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
</head>
<body>
<div class="container mt-3">
    {% block content %}
    {% endblock content %}
</div>
{% block scripts %}
{% endblock scripts %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>
</html>